POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhYWJlIiwiaWQiOiI2ODljNjVhMDk4YmNkYmZhZjgzMmQ1ODciLCJpYXQiOjE3NTUwODI2NzZ9.3JCDpafAJJw_237aij4gJYfLESLABx_KGH7IwzdAg_4

{ "author": "Esco", "title": "Urjalasta kajahtaa spradam", "url": "www.example.com/lamb", "likes": 2, "user": "689b91b4200cebc5219c501b" }